### ISSUE TITLE
Callbacks sensitive on timing

### ISSUE THREAD

**Issue by githubnemo** [ytakano/libcage#1]
It seems that the callbacks are very sensitive on timing. If execution of a callback (join, for example)
takes to much time, the join fails.

How to reproduce:
For an executable example see https://gist.github.com/098e0a3bec1e8059c529.

Otherwise, build up a join callback, sleep 2-3 seconds in there and see the join failing.

**Comment by ytakano** [comment]
Thank you very much. I fixed this problem.
