### ISSUE TITLE
Long messages result in segfault

### ISSUE THREAD

**Issue by githubnemo** [ytakano/libcage#3]
If one sends a long (38325 bytes in my case) message directly to a peer it results in a segmentation fault 
at the `memcpy` in `dgram::push2queue`

```
 p = pbuf->append(len);
 memcpy(p, msg, len);
```

The size check in `pbuf->append` results in `p = NULL` which is not checked.

I'm not sure how to deal with this so I'm not supplying a patch, sorry.

**Comment by ytakano** [comment]
Thank you. I'll check it next week.

**Comment by ytakano** [comment]
Fixed.

If the length is bigger than 896 bytes, the message is automatically divided and then delivered to the destination unlike UDP.
The destination node should be receive multiple times.

void send_dgram(const void *buf, int len, uint8_t *dst);
