### ISSUE TITLE
The example2 question

### ISSUE THREAD

**Issue by wzx011011** [ytakano/libcage#6]
The example2 join 100 nodes to the network.
Does it need a server?
Thanks

**Comment by ytakano** [comment]
No, you don't need server.

Two boot strap nodes are created from L81 to L102.
https://github.com/ytakano/libcage/blob/90d4d63caf9a05b711d99d6c32719f0f69d7d22b/example/example2.cpp#L81-L102

Then, other nodes join to the network via the boot strap node.
https://github.com/ytakano/libcage/blob/90d4d63caf9a05b711d99d6c32719f0f69d7d22b/example/example2.cpp#L36-L44

**Comment by wzx011011** [comment]
well,I have another question. Now I use example5 to create a server and client solution.After i install server solution on a Server with public IP,and two client connect the server.How can a client send to another, have a detail example?
Thanks!
